version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.20
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-193-0.compute-1.amazonaws.com
            port: '5432'
            database: debpp2dl6atncd
            ssl: true
            user: ynabijvxgyvgan
            password: 75e80639c249b5e86bedf303df8ee1e78caebe94226258ab063a958073fb96fd
            migrations: true
            rawAccess: true